version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb+srv://dahuizhusong:QxKbmBzJ55CqUAw0@cluster0.ijfwg.mongodb.net/?retryWrites=true&w=majority
      - SECRET_LOVE=your_secret_key
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data: